apiVersion: apps/v1
kind: Deployment
metadata:
  name: sangsiklog-web
  labels:
    app: sangsiklog-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sangsiklog-web
  template:
    metadata:
      labels:
        app: sangsiklog-web
    spec:
      containers:
        - name: sangsiklog-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}