apiVersion: v1
kind: Service
metadata:
  name: sangsiklog-web
  labels:
    app: sangsiklog-web
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: sangsiklog-web