version: '3.8'

services:
  sangsiklog-web:
    image: sangsiklog-web-local:latest
    container_name: sangsiklog-web
    ports:
      - "80:80"
    networks:
      - sangsiklog-network

networks:
  sangsiklog-network:
    driver: bridge